/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islibrary.screen;

import islibrary.adapter.TableAdapter;
import islibrary.data.BookModel;
import islibrary.data.ReaderBookPair;
import islibrary.data.ReaderModel;
import islibrary.util.DataSaver;
import islibrary.util.Util;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author АРИНА
 */
public class IssuedBooks extends javax.swing.JFrame {

    TableAdapter<ReaderBookPair> adapter;
    OnIssueCallback callback;

    public IssuedBooks(OnIssueCallback callback) {
        this.callback = callback;
        initComponents();

        adapter = new TableAdapter<ReaderBookPair>(jTable1);
        init();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    ArrayList<ReaderBookPair> getPairList() {
        return DataSaver.getInstance().readerBookPairSource.readObject();
    }

    final void init() {
        DefaultTableModel modelTable = new DefaultTableModel(new Object[]{
            "Билет",
            "ФИО",
            "Дата выдачи",
            "Дата возврата",
            "Возвращена"
        }, 0);

        ArrayList<ReaderBookPair> list = getPairList();

        adapter.initItems(list, modelTable, (ReaderBookPair model) -> {
            String isIssuedString;
            if (model.wasIssued()) {
                isIssuedString = Util.longToDateString(model.isIssueDate);
            } else {
                isIssuedString = "-";
            }
            
            ReaderModel reader = DataSaver.getInstance().readersDataSource.findModelByNumber(Integer.toString(model.readerNumber));

            return new Object[]{
                model.bookNumber,
                reader.getFullname(),
                Util.longToDateString(model.issueDate),
                Util.longToDateString(model.returnDate),
                isIssuedString
            };
        });

        jTable1.setModel(modelTable);
    }

    void issueSelectedPair() {
        ReaderBookPair selectedPair = adapter.getSelectedModel();
        selectedPair.isIssueDate = System.currentTimeMillis();
        DataSaver.getInstance().readerBookPairSource.writeObject(selectedPair);
        
        BookModel targetBook = DataSaver.getInstance().bookDataSource.findModelByNumber(Integer.toString(selectedPair.bookNumber));
        targetBook.count++;
        DataSaver.getInstance().bookDataSource.writeObject(targetBook);
        
        callback.onBookIssued();

        init();
    }

    public static void showDialog(OnIssueCallback callback) {
        IssuedBooks issuedBooks = new IssuedBooks(callback);
        issuedBooks.setVisible(true);
        issuedBooks.setSize(700, 400);
        issuedBooks.setTitle("Абонементы");
    }

    public interface OnIssueCallback {
        void onBookIssued();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Книга");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Вернуть экземпляр");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Закрыть");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        issueSelectedPair();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
