/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islibrary.screen;

import islibrary.models.BookModel;
import islibrary.util.DataSaver;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author АРИНА
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setListByQuery("");
    }
    
    private void setListByQuery(String query) {
        ArrayList<BookModel> list = getListByQuery(query);
        DefaultTableModel model = new DefaultTableModel(new Object[]{"№", "Наименование" ,"Автор", "Год", "Количетво страниц", "Издательство"},0);
        
        list.forEach((book) -> {
            model.addRow(new Object[]{
                book.number,
                book.name,
                book.author,
                book.yearBook,
                book.pages,
                book.publis
            });
        });
        
        jTable1.setModel(model);
    }
    
    private ArrayList<BookModel> getListByQuery(String query) {
        ArrayList<BookModel> list = getList();
        ArrayList<BookModel> result = new ArrayList<>();
        
        list.forEach((book) -> {
            if(book.isMatchByQuery(query)) result.add(book);
        });
        
        return result;
    }

    private ArrayList<BookModel> getList() {
        try {
            return DataSaver.BookSaver.readObject();
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return new ArrayList<>();
    }
    
    public static void showModel () {
        MainScreen mainScreen = new MainScreen();
        mainScreen.setVisible(true);
        mainScreen.setSize(680, 420);
        mainScreen.setTitle("Библиотека");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textFieldSearchBooks = new javax.swing.JTextField();
        labelSearch = new javax.swing.JLabel();
        buttonSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIssuedBooks = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemIssueBook = new javax.swing.JMenuItem();
        menuItemIssuedBooks = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRegister = new javax.swing.JMenuItem();
        menuReaders = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(60, 100));
        jTable1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        labelSearch.setText("Поиск");

        buttonSearch.setText("Найти");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        menuIssuedBooks.setText("Книги");

        jMenuItem1.setText("Добавить");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuIssuedBooks.add(jMenuItem1);

        jMenuItem2.setText("Изменить");
        menuIssuedBooks.add(jMenuItem2);

        jMenuItem3.setText("Удалить");
        menuIssuedBooks.add(jMenuItem3);

        menuItemIssueBook.setText("Выдать");
        menuItemIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIssueBookActionPerformed(evt);
            }
        });
        menuIssuedBooks.add(menuItemIssueBook);

        menuItemIssuedBooks.setText("Выданные экземпляры");
        menuItemIssuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIssuedBooksActionPerformed(evt);
            }
        });
        menuIssuedBooks.add(menuItemIssuedBooks);

        jMenuBar1.add(menuIssuedBooks);

        jMenu2.setText("Читатели");

        menuRegister.setText("Регистрация");
        menuRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegisterActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegister);

        menuReaders.setText("Карточка читателя");
        menuReaders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReadersActionPerformed(evt);
            }
        });
        jMenu2.add(menuReaders);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldSearchBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearch)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSearch)
                    .addComponent(textFieldSearchBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddBook.showDialog(() -> {
            setListByQuery("");
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegisterActionPerformed
        RegisterReader.showDialog();
    }//GEN-LAST:event_menuRegisterActionPerformed

    private void menuReadersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReadersActionPerformed
        ReadersList.showDialog();
    }//GEN-LAST:event_menuReadersActionPerformed

    private void menuItemIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIssueBookActionPerformed
        IssueBook.showDialog();
    }//GEN-LAST:event_menuItemIssueBookActionPerformed

    private void menuItemIssuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIssuedBooksActionPerformed
        IssuedBooks.showDialog();
    }//GEN-LAST:event_menuItemIssuedBooksActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        String query = textFieldSearchBooks.getText();
        setListByQuery(query);
    }//GEN-LAST:event_buttonSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearch;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JMenu menuIssuedBooks;
    private javax.swing.JMenuItem menuItemIssueBook;
    private javax.swing.JMenuItem menuItemIssuedBooks;
    private javax.swing.JMenuItem menuReaders;
    private javax.swing.JMenuItem menuRegister;
    private javax.swing.JTextField textFieldSearchBooks;
    // End of variables declaration//GEN-END:variables
}
