/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package islibrary.screen;

import islibrary.models.ReaderModel;
import islibrary.util.Util;
import islibrary.dialog.DialogCalendar;
import islibrary.dialog.DialogMessage;
import islibrary.util.DataSaver;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author АРИНА
 */
public class RegisterReader extends javax.swing.JFrame {

    long date;
    Callabck callback;
    /**
     * Creates new form RegisterReader
     */
    public RegisterReader() {
        initComponents();
        init();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public RegisterReader(ReaderModel editReader, Callabck callback) {
        this.callback = callback;
        initComponents();
        initComponents(editReader);
        
        
        init();
        labelIssueBooks.setText(Integer.toString(editReader.issuedBook));
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    void init() {
        boolean isEdit = isEditMode();
        
        labelBooksIssued.setVisible(isEdit);
        labelSettings.setVisible(isEdit);
        labelIssueBooks.setVisible(isEdit);
    }
    
    void initComponents(ReaderModel editReader) {
        textFieldNumberBilet.setEditable(false);
        
        date = editReader.dateOfBirth;
        textFieldNumberBilet.setText(Integer.toString(editReader.numberBilet));
        textFieldLomit.setText(Integer.toString(editReader.limit));
        textFieldFirstName.setText(editReader.firstName);
        textFieldSecondName.setText(editReader.lastName);
        textFieldFather.setText(editReader.secondName);
        textFieldAdress.setText(editReader.adress);
        textFieldPhoneNumber.setText(editReader.numberPhone);
        textFieldSelectedDate.setText(Util.longToDateString(editReader.dateOfBirth));
    }
    
    boolean isEditMode() {
        return callback != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        labelNumberBilet = new javax.swing.JLabel();
        textFieldNumberBilet = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        textFieldFirstName = new javax.swing.JTextField();
        labelSekondName = new javax.swing.JLabel();
        textFieldSecondName = new javax.swing.JTextField();
        labelAdress = new javax.swing.JLabel();
        textFieldAdress = new javax.swing.JTextField();
        labelPhoneNumber = new javax.swing.JLabel();
        textFieldPhoneNumber = new javax.swing.JTextField();
        labelDateOfBirth = new javax.swing.JLabel();
        labelLimit = new javax.swing.JLabel();
        textFieldLomit = new javax.swing.JTextField();
        labelSettings = new javax.swing.JLabel();
        labelBooksIssued = new javax.swing.JLabel();
        labelFather = new javax.swing.JLabel();
        textFieldFather = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonSelectDateBirth = new javax.swing.JButton();
        labelSelectedDateBirth = new javax.swing.JLabel();
        textFieldSelectedDate = new javax.swing.JTextField();
        labelIssueBooks = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNumberBilet.setText("Номер билета");

        labelFirstName.setText("Имя");

        textFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFirstNameActionPerformed(evt);
            }
        });

        labelSekondName.setText("Фамилия ");

        labelAdress.setText("Адрес");

        labelPhoneNumber.setText("Телефон");

        textFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPhoneNumberActionPerformed(evt);
            }
        });

        labelDateOfBirth.setText("Дата рождения ");

        labelLimit.setText("Лимит");

        labelSettings.setText("Сведения");

        labelBooksIssued.setText("Выдано книг: ");

        labelFather.setText("Отчество");

        buttonSave.setText("Сохранить");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonCancel.setText("Отмена");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonSelectDateBirth.setText("Выбрать");
        buttonSelectDateBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectDateBirthActionPerformed(evt);
            }
        });

        labelIssueBooks.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelBooksIssued)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelIssueBooks))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLimit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(labelPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSekondName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldSecondName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(textFieldAdress)
                            .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(textFieldLomit, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(textFieldFather, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(buttonSelectDateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldSelectedDate))
                        .addGap(18, 18, 18)
                        .addComponent(buttonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSelectedDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumberBilet, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNumberBilet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumberBilet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldNumberBilet, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(labelSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBooksIssued)
                            .addComponent(labelIssueBooks))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(labelSelectedDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldFather, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSekondName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSelectDateBirth)
                            .addComponent(textFieldSelectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldLomit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSave)
                            .addComponent(buttonCancel))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFirstNameActionPerformed

    private void textFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPhoneNumberActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
       saveReader();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonSelectDateBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectDateBirthActionPerformed
        DialogCalendar.pickdate(new DialogCalendar.DateCallback() {
            @Override
            public void onSelectDate(long Date) {
                     date = Date;
                textFieldSelectedDate.setText(Util.longToDateString(Date));
            }
        });
    }//GEN-LAST:event_buttonSelectDateBirthActionPerformed
    
    public static void showDialog() {
        RegisterReader dialog = new RegisterReader();
        dialog.setVisible(true);
        dialog.setSize(640, 480);
        dialog.setTitle("Регистрация читателя");
    }
    
    public static void showDialog(ReaderModel reader, Callabck callback) {
        RegisterReader dialog = new RegisterReader(reader, callback);
        dialog.setVisible(true);
        dialog.setSize(640, 480);
        dialog.setTitle("Редактирование читателя");
    }

    void saveReader() {
        int NumberBilet;
        if (numberBiletIsValid()) {
            NumberBilet = Integer.parseInt(textFieldNumberBilet.getText());
        } else {
            DialogMessage.showMessage("Номер билета должен быть введенн корректно!");
            return;
        }
        if (date == 0) {
            DialogMessage.showMessage("Не была введенна дата!");
            return;
        }
        int limit;
        if (limitIsValid()) {
            limit = Integer.parseInt(textFieldLomit.getText());
        } else {
            DialogMessage.showMessage("Неправильно задан лимит!");
            return;
        }
        
        if(limit > 20) {
            DialogMessage.showMessage("Лимит книг не должен превышать 20!");
            return;
        }
        
        if(!Util.stringIsLetters(textFieldFirstName.getText())) {
            DialogMessage.showMessage("Введите корректное имя!");
            return;
        }
        
        if(textFieldFirstName.getText().isEmpty()) {
            DialogMessage.showMessage("Поле Имя не может быть пустым!");
            return;
        }
        
        if(!Util.stringIsLetters(textFieldSecondName.getText())) {
            DialogMessage.showMessage("Введите корректную фамилию!");
            return;
        }
 
        if(textFieldSecondName.getText().isEmpty()) {
            DialogMessage.showMessage("Поле Фамилия не может быть пустым!");
            return;
        }
        
        if(!Util.stringIsNumberPhone(textFieldPhoneNumber.getText())) {
            DialogMessage.showMessage("Введите номер телефона в формате: 9999999999, 1-999-999-9999 или 999-999-9999!");
            return;
        }
        
        ReaderModel data = new ReaderModel(
                NumberBilet,
                textFieldFirstName.getText(),
                textFieldFather.getText(),
                textFieldSecondName.getText(),
                textFieldAdress.getText(),
                textFieldPhoneNumber.getText(),
                date,
                limit,
                0
        );

        DataSaver.ReadersModelSaver.getInstance().writeObject(data);
        if(isEditMode()) callback.onReaderEdited();
        dispose();

    }

    boolean numberBiletIsValid() {
        return Util.isInteger(textFieldNumberBilet.getText());
    }

    boolean limitIsValid() {
        return Util.isInteger(textFieldLomit.getText());
    }
    
    public interface Callabck {
        void onReaderEdited();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonSelectDateBirth;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAdress;
    private javax.swing.JLabel labelBooksIssued;
    private javax.swing.JLabel labelDateOfBirth;
    private javax.swing.JLabel labelFather;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelIssueBooks;
    private javax.swing.JLabel labelLimit;
    private javax.swing.JLabel labelNumberBilet;
    private javax.swing.JLabel labelPhoneNumber;
    private javax.swing.JLabel labelSekondName;
    private javax.swing.JLabel labelSelectedDateBirth;
    private javax.swing.JLabel labelSettings;
    private javax.swing.JTextField textFieldAdress;
    private javax.swing.JTextField textFieldFather;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldLomit;
    private javax.swing.JTextField textFieldNumberBilet;
    private javax.swing.JTextField textFieldPhoneNumber;
    private javax.swing.JTextField textFieldSecondName;
    private javax.swing.JTextField textFieldSelectedDate;
    // End of variables declaration//GEN-END:variables
}
